spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:testdb
    password: test

  h2:
    console.path: /h2

  devtools:
    restart:
      enabled: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations:
      - classpath:db/migration

server:
  port: 4444

size-measures:
  extra-small: xs
  small: s
  medium: m
  large: l
  extra-large: xl