spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: jijojos

  devtools:
    restart:
      enabled: true

server:
  port: 4444

size-measures:
  extra-small: xs
  small: s
  medium: m
  large: l
  extra-large: xl