apiVersion: apps/v1
kind: Deployment
metadata:
  name: jersey-house-backend
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jersey-house-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jersey-house-backend
    spec:
      containers:
        - image: gcr.io/love4messi/jersey-house-backend:latest
          imagePullPolicy: Always
          name: jersey-house-backend
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always