apiVersion: v1
kind: Service
metadata:
  name: jersey-house-backend-service
spec:
  selector:
    app: jersey-house-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4444
  type: LoadBalancer