INSERT INTO COUNTRY (country_code, country_name) VALUES(1, 'SAMPLE_COUNTRY');
INSERT INTO LEAGUE (LEAGUE_CODE, LEAGUE_NAME) VALUES (1, 'SAMPLE League');
INSERT INTO  league_availability  (id,country_code, LEAGUE_CODE) VALUES  (1, 1, 1);
INSERT INTO  season  (SEASON_CODE, START_YEAR, END_YEAR) VALUES  (1, 2000, 2001);