INSERT INTO LEAGUE (LEAGUE_CODE, LEAGUE_NAME) VALUES (1, 'English Premier League');
INSERT INTO LEAGUE (LEAGUE_CODE, LEAGUE_NAME) VALUES (2, 'Spanish League');
INSERT INTO LEAGUE (LEAGUE_CODE, LEAGUE_NAME) VALUES (3, 'Ligue 1');
INSERT INTO LEAGUE (LEAGUE_CODE, LEAGUE_NAME) VALUES (4, 'SERIA A');
INSERT INTO LEAGUE (LEAGUE_CODE, LEAGUE_NAME) VALUES (5, 'ISL');
INSERT INTO LEAGUE (LEAGUE_CODE, LEAGUE_NAME) VALUES (6, 'BUNDESLIGA');