CREATE TABLE LEAGUE_AVAILABILITY (
   ID INT NOT NULL,
   LEAGUE_CODE INT NOT NULL,
   COUNTRY_CODE INT NOT NULL,
   CONSTRAINT pk_leagueavailability PRIMARY KEY (ID),
   FOREIGN KEY (LEAGUE_CODE) REFERENCES LEAGUE(LEAGUE_CODE),
   FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRY(COUNTRY_CODE)
);