CREATE TABLE SEASON (
  SEASON_CODE INT NOT NULL,
   START_YEAR INT NOT NULL,
   END_YEAR INT NOT NULL,
   CONSTRAINT pk_season PRIMARY KEY (SEASON_CODE)
);

ALTER TABLE SEASON ADD CONSTRAINT uc_season_endyear UNIQUE (END_YEAR);

ALTER TABLE SEASON ADD CONSTRAINT uc_season_startyear UNIQUE (START_YEAR);